my_dbt_project_test:
  target: prod
  outputs:

    prod:
      dataset: my_dbt_project
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU # (EU, US)
      method: oauth
      priority: interactive
      project: data-science-on-gcp-323609
      threads: 4
      type: bigquery
    
    dev:
      dataset: mh_my_dbt_project
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU # (EU, US)
      method: oauth # can change to service-account
      # keyfile: # if using service-account for authentication
      priority: interactive
      project: data-science-on-gcp-323609
      threads: 4
      type: bigquery   
